.TH "LSurveyParserException" 3 "Fri Mar 6 2020" "Version 1.0" "LSurveyParser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LSurveyParserException
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.PP
Inherited by \fBSurveyException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($message=null, $code=null)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$message\fP = 'Unknown error'"
.br
.ti -1c
.RI "\fB$code\fP = 0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $message = \fCnull\fP,  $code = \fCnull\fP)"
\fBLSurveyParserException\fP constructor\&.
.PP
\fBAuthor\fP
.RS 4
Tiziano Marra https://github.com/MrTiz 
.RE
.PP
\fBSince\fP
.RS 4
1\&.0
.RE
.PP
\fBParameters\fP
.RS 4
\fI$message\fP Error message 
.br
\fI$code\fP Error code 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for LSurveyParser from the source code\&.
