.TH "LSurveyParser" 3 "Fri Mar 6 2020" "Version 1.0" "LSurveyParser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LSurveyParser
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBDatabase\fP"
.br
.ti -1c
.RI "interface \fBILSurveyParser\fP"
.br
.ti -1c
.RI "class \fBLSurveyParserException\fP"
.br
.ti -1c
.RI "class \fBParser\fP"
.br
.ti -1c
.RI "class \fBSurveyException\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
@Copyright (c) 2020 Tiziano Marra https://github.com/MrTiz9\&.
.PP
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License along with this program\&. if not, see https://www.gnu.org/licenses/\&.
.PP
\fBAuthor\fP
.RS 4
Tiziano Marra https://github.com/MrTiz9 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0
.RE
.PP
Class \fBDatabase\fP
.PP
\fBAuthor\fP
.RS 4
Tiziano Marra https://github.com/MrTiz9 
.RE
.PP
\fBSince\fP
.RS 4
1\&.0
.RE
.PP
Class \fBLSurveyParserException\fP
.PP
\fBAuthor\fP
.RS 4
Tiziano Marra https://github.com/MrTiz9 
.RE
.PP
\fBSince\fP
.RS 4
1\&.0
.RE
.PP
Class \fBSurveyException\fP
.PP
\fBAuthor\fP
.RS 4
Tiziano Marra https://github.com/MrTiz9 
.RE
.PP
\fBSince\fP
.RS 4
1\&.0
.RE
.PP
Interface \fBILSurveyParser\fP
.PP
\fBAuthor\fP
.RS 4
Tiziano Marra https://github.com/MrTiz9 
.RE
.PP
\fBSince\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for LSurveyParser from the source code\&.
