.TH "SurveyException" 3 "Fri Mar 6 2020" "Version 1.0" "LSurveyParser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SurveyException
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLSurveyParserException\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for LSurveyParser from the source code\&.
