.TH "Parser" 3 "Fri Mar 6 2020" "Version 1.0" "LSurveyParser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Parser
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Class \fBParser\fP
.PP
\fBAuthor\fP
.RS 4
Tiziano Marra https://github.com/MrTiz9 
.RE
.PP
\fBSince\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for LSurveyParser from the source code\&.
